#pragma config(Sensor, S1,     button,         sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int time;
	time = 2000;
	int speedleft;
	speedleft = 10;
	int speedright;
	speedright = 20;
	while(true)
	{
	motor(motorB)= speedleft;
	motor(motorA)= speedright;
	wait1Msec(4000);
	if(SensorValue(button) == 1)
	{
	motor(motorA)= -50;
	motor(motorB)= -90;
	wait1Msec(1000);
	motor(motorA)= 70;
	motor(motorB)= 100;
	wait1Msec(1500);
	}
	speedright = speedright + 15;
	speedleft = speedleft + 10;
	}
  if(SensorValue(button)== 0)
  {
  motor(motorB)= -80;
  motor(motorA)= -50;
  wait1Msec(1500);
	}
  motor(motorA)= 70;
  motor(motorB)= 100;

    if(getMotorEncoder(motorA) > 2000)
  {
  motor(motorA)= 100;
  motor(motorB)= 100;


}

}
