#pragma config(Sensor, S1,     button,         sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true)
  {
  if(SensorValue(button)== 1)
  {
  motor(motorB)= -80;
  motor(motorA)= -50;
  wait1Msec(1500);
	}
  motor(motorA)= 70;
  motor(motorB)= 100;

    if(getMotorEncoder(motorA) > 2000)
  {
  motor(motorA)= 100;
  motor(motorB)= 100;
}
else
{
}
}
}
